export const ESSAY_PROMPTS: string[] = [
  "Can characters or events in books and stories teach useful lessons?",
  "Can a group of people function effectively when no one is in charge?",
  "Do books based on ideas and fiction offer any real advantage to the reader?",
  "Should we change ourselves without limits, or only make a few important changes in life?",
  "Have modern society's conveniences become nuisances that cause depression instead of saving time and energy?",
  "Is it wrong or harmful to motivate people to learn or achieve by offering rewards?",
  "Has the acquisition of possessions replaced the real measure of achievement?",
  "Should we seek others' opinions, or focus on developing our own ideas?",
  "Are people happier when they focus on goals other than their own happiness?",
  "Do people put too much emphasis on learning practical skills?",
  "Can deception — pretending to act in a certain way when it is not true — sometimes lead to good results?",
  "Can you control your happiness, or is happiness not in your control?",
  "Does history hold value for the present generation?",
  "Should you wear a tie to an interview?",
  "What does happiness mean to you?",
  "Should parents give their children an allowance?",
  "Should people be optimistic or realistic?",
  "Should tax money be spent on space exploration, or on issues here on Earth?",
  "Is success the result of hard work, or driven by luck?",
  "Is it necessary to make mistakes even if they cause negative consequences for other people?",
  "What is more valuable: fitting in, or being different and unique?",
  "Is it better to be original than to imitate others?",
  "Is it necessary to find new solutions to problems, or can we rely on existing ones?",
];
